utils::globalVariables(
  c(
    ".",
    "GENESIS_source",
    "GENESIS_source_nr",
    "id",
    "name",
    "param_name",
    "param_description",
    "stat_description_full",
    "stat_description_full_en",
    "year",
    "n",
    "year_id",
    "dg_descriptions",
    "dg_regions",
    "value"
  )
)